### ISSUE TITLE
White armbands

### ISSUE THREAD

**Issue by michaelconnor** [frombeirutwithlove/ProtestTips#6]
"In NYC specifically, undercover police are easily spotted as having a white band around their arm, like this."

I don't know that this is true anymore, but I think it's changed.

**Comment by bhavika** [comment]
NYPD and some other police departments operate on Color of the day https://en.wikipedia.org/wiki/Color_of_the_day_(police) so yeah, it's not just white bands.

**Comment by frombeirutwithlove** [comment]
Just updated it, thanks both.
